terrains:
  - id: 1
    key: sea
    rgb: [50, 56, 200]
    forbidden: true
    outline: water
  - id: 2
    key: river
    rgb: [43, 113, 223]
    forbidden: true
    outline: water
  - id: 3
    key: plains
    rgb: [58, 200, 50]
    forbidden: false
    outline: land
  - id: 4
    key: forest
    rgb: [27, 122, 38]
    forbidden: false
    outline: land
  - id: 5
    key: hills
    rgb: [147, 155, 137]
    forbidden: false
    outline: land
  - id: 6
    key: mountain
    rgb: [203, 206, 198]
    forbidden: false
    outline: land

prefer_aliases:
  water: [sea, river]
